<?php defined('_ROOT') or die('Not Allowed');
$merge_block = 7;
$_tpl = '﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	Website generated by CMS v02
	URL: http://demo.phpbasic.com
	Email: w2ajax@gmail.com
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" href="../template/Default/style/font-awesome.css" type="text/css" media="all">
<link rel="stylesheet" type="text/css" href="../template/Default/style/font-awesome-animation.min.css" media="all"/>

<link rel="stylesheet" type="text/css" href="template/css/common.css" />
<link rel="icon" href="../favicon.ico" type="image/x-icon" />
<title>CMS - '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</title>       
<script>var token  = \''.(isset($this->_data["."][0]['token'])?$this->_data["."][0]['token']:'').'\';</script>
<!--<script type="text/javascript" src="../plugins/jquery-1.11.1.min.js"></script>-->
<script type="text/javascript" src="../plugins/jquery-1.3.2.min.js"></script>

<script type="text/javascript" src="../template/Default/js/jquery.form.min.js"></script>



<script>var plugins_dir = \'../\';var root_dir = \''.(isset($this->_data["."][0]['root_dir'])?$this->_data["."][0]['root_dir']:'').'\'; var lang = \''.(isset($this->merge['system']['lang'])?$this->merge['system']['lang']:'').'\';</script>
<script type="text/javascript" src="../plugins/tableorder/jquery.tableorder.js"></script>
<script type="text/javascript" src="template/js/common.js"></script>
<script type="text/javascript" src="template/js/module.configure.js"></script>

<script type="text/javascript" src="../plugins/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="template/js/editor.js"></script>

<script type="text/javascript" src="../plugins/ckeditor/ckeditor.js"></script>

<script type="text/javascript" src="../plugins/divbox/divbox.js"></script>
<link rel="stylesheet" href="../plugins/divbox/css/frontend.css" type="text/css" media="screen" />
<script type="text/javascript">
var access_new = \''.(isset($this->merge['access']['new'])?$this->merge['access']['new']:'').'\';
var access_edit = \''.(isset($this->merge['access']['edit'])?$this->merge['access']['edit']:'').'\';
var access_delete = \''.(isset($this->merge['access']['delete'])?$this->merge['access']['delete']:'').'\';
</script>
<script type="text/javascript" src="../plugins/validate/validate.js"></script>
<link rel="stylesheet" href="../plugins/validate/css/validate.css" type="text/css" media="screen" />
<script type="text/javascript" src="../plugins/dateinput/dateinput.js"></script>
<!--<script type="text/javascript" src="../plugins/jquery.slug.js"></script>-->
<script type="text/javascript">
$(document).ready(function(){
	$.each($(\'form input[type=text]\'),function(i,val){
		var id = $(val).attr(\'name\');	
		id = id.replace("[","_");
		id = id.replace("]","");
		if($(val).attr(\'id\') == "" || $(val).attr(\'id\')  == undefined){
			$(val).attr(\'id\',id);
			$(val).addClass(id);
		}
	});
	//$("#name_vn").slug();
	
});
</script>

<script type="text/javascript">
$(document).ready(function(){
	$(".mtitle_vn").attr(\'maxlength\',\'60\');
	$(".mdesc_vn").attr(\'maxlength\',\'300\');
	$(\'.view_vn\').css({backgroundColor:"#fcebac"});
	$(\'.name_seo_vn\').css({backgroundColor:"#dadada"});	
});
</script>
<script type="text/javascript" src="template/skins/default/js/common.js"></script>
<link rel="stylesheet" type="text/css" href="template/skins/default/css/style.css" />
<!--[if IE]>
<style type="text/css">
tr.show{ display: block; }
</style>
<![endif]--> 

</head>
<body>

<div class="wrapper">
	<div class="container">
		<div class="hd">
			<p class="hd-r">
				Welcome <span class="hd-username">'.(isset($this->merge['login_user']['fullname'])?$this->merge['login_user']['fullname']:'').'</span>, 
				<a href="?mod=user&act=update" class="hd-profile">'.(isset($this->merge['lang']['update_profile'])?$this->merge['lang']['update_profile']:'').'</a> or 
				<a href="?mod=user&act=reset" class="hd-resetPass">'.(isset($this->merge['lang']['reset_password'])?$this->merge['lang']['reset_password']:'').'</a> <span class="hd-divider">|</span> 
				<a href="?mod=user&act=logout" class="hd-logout">'.(isset($this->merge['lang']['logout'])?$this->merge['lang']['logout']:'').'</a>
			</p>
			<a class="hd-logo" href="./">'.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</a>
		</div>
		
		<div class="ct">
			<div class="side">
				<!--<p class="menu-des">Menu</p>
				<p class="menu-desSub">
					Manage the site by this menu.<br />
					Click to collapse the menu.
				</p>-->
				';if(isset($this->_data['leftmenu.'])){for($i=0;$i< count($this->_data['leftmenu.']);$i++){$_tpl .= '
				<div class="menu '.(isset($this->_data["leftmenu."][$i]["cls_cms"])?$this->_data["leftmenu."][$i]["cls_cms"]:'').'">
					<h2 id="'.(isset($this->_data["leftmenu."][$i]["id"])?$this->_data["leftmenu."][$i]["id"]:'').'menu">'.(isset($this->_data["leftmenu."][$i]["name"])?$this->_data["leftmenu."][$i]["name"]:'').'</h2>
					'.(isset($this->_data["leftmenu."][$i]["links"])?$this->_data["leftmenu."][$i]["links"]:'').'
				</div>
				';}}$_tpl .= '
			</div>
			
			<div class="main">
				<div class="mainInner">
					<div class="breadcrumb">'.(isset($this->_data["."][0]['breadcrumb'])?$this->_data["."][0]['breadcrumb']:'').'</div>
					<div class="module_description">'.(isset($this->_data["."][0]['module_description'])?$this->_data["."][0]['module_description']:'').'</div>				
					<form name="form1" method="post" action="">
<p>Module: <strong>content</strong> <br />
  Type Id: #<strong>'.(isset($this->_data["."][0]['typeid'])?$this->_data["."][0]['typeid']:'').'</strong></p>
<p>&nbsp;</p>
<table width="100%" border="0" cellspacing="1" cellpadding="1" class="table-Form1 table_list">
    <tr>
      <td bgcolor="#CCCCCC">General</td>
      <td bgcolor="#CCCCCC">&nbsp;</td>
    </tr>
        <tr>
        <td width="21%">Name</td>
        <td width="79%"><input name="name" class="no_width" type="text" id="name" value="'.(isset($this->_data["."][0]['name'])?$this->_data["."][0]['name']:'').'" /></td>
      </tr>
      <tr>
        <td>Description</td>
        <td><textarea name="content" rows="3" class="no_width">'.(isset($this->_data["."][0]['content'])?$this->_data["."][0]['content']:'').'</textarea></td>
      </tr>
      <tr>
        <td>Languages</td>
        <td><select name="languages">
          <option value="0">All</option>
		  <option value="1" '.(isset($this->_data["."][0]['selected_languages_1'])?$this->_data["."][0]['selected_languages_1']:'').'>Default language</option>
        </select>        </td>
      </tr>    <tr>
    <td>SEO Manage </td>
    <td><input name="act[]" type="checkbox" class="no_width" id="act[]" value="meta_data" '.(isset($this->_data["."][0]['meta_data_checked'])?$this->_data["."][0]['meta_data_checked']:'').' />
Meta data 
  <input name="act[]" type="checkbox" class="no_width" id="act[]" value="seo_url" '.(isset($this->_data["."][0]['seo_url_checked'])?$this->_data["."][0]['seo_url_checked']:'').' />  SEO URL</td>
  </tr>
    <tr>
      <td>Text Editor </td>
      <td><input name="act[]" type="checkbox" id="act[]" value="enable_editor"  '.(isset($this->_data["."][0]['enable_editor_checked'])?$this->_data["."][0]['enable_editor_checked']:'').' class="no_width" /> 
         Enable TinyMCE </td>
    </tr>
    <tr>
      <td>Search function </td>
      <td><input name="act[]" type="checkbox" id="act[]" value="enable_search"  '.(isset($this->_data["."][0]['enable_search_checked'])?$this->_data["."][0]['enable_search_checked']:'').' class="no_width" /> 
      Enable search function </td>
    </tr>
	<tr>
    <td valign="top">Default sort </td>
    <td>by 
      <select name="sort_default" id="sort_default">
      <option value="order_id" '.(isset($this->_data["."][0]['sort_default_order_id'])?$this->_data["."][0]['sort_default_order_id']:'').'>Order Id</option>
      <option value="name" '.(isset($this->_data["."][0]['sort_default_name'])?$this->_data["."][0]['sort_default_name']:'').'>Name</option>
      <option value="date" '.(isset($this->_data["."][0]['sort_default_date'])?$this->_data["."][0]['sort_default_date']:'').'>Date</option>
      <option value="status" '.(isset($this->_data["."][0]['sort_default_status'])?$this->_data["."][0]['sort_default_status']:'').'>Status</option>
    </select>
      <input name="sort_default_order" type="text" id="sort_default_order" value="'.(isset($this->_data["."][0]['sort_default_order'])?$this->_data["."][0]['sort_default_order']:'').'" /></td>
  </tr>


    <tr>
      <td valign="top">Labels <a href="#" onclick="add_buttons();">[+]</a> </td>
      <td><table width="100%" border="0" cellspacing="1" cellpadding="1" id="add_button" class="hide" >
        <tr>
          <td width="21%">Root</td>
          <td width="79%"><input name="button[root]" type="text" id="button[root]" value="'.(isset($this->merge['button']['root'])?$this->merge['button']['root']:'').'" /></td>
        </tr>
        <tr>
          <td>Header &gt; Name </td>
          <td><input name="button[header_name]" type="text" id="button[header_name]" value="'.(isset($this->merge['button']['header_name'])?$this->merge['button']['header_name']:'').'" /></td>
        </tr>
        <tr>
          <td>Header &gt; Date </td>
          <td><input name="button[header_date]" type="text" id="button[header_date]" value="'.(isset($this->merge['button']['header_date'])?$this->merge['button']['header_date']:'').'" /></td>
        </tr>
        <tr>
          <td>Header &gt; Order </td>
          <td><input name="button[header_order]" type="text" id="button[header_order]" value="'.(isset($this->merge['button']['header_order'])?$this->merge['button']['header_order']:'').'" /></td>
        </tr>
        <tr>
          <td>Header &gt; Status </td>
          <td><input name="button[header_status]" type="text" id="button[header_status]" value="'.(isset($this->merge['button']['header_status'])?$this->merge['button']['header_status']:'').'" /></td>
        </tr>
        <tr>
          <td>Header &gt; Actions</td>
          <td><input name="button[header_actions]" type="text" id="button[header_actions]" value="'.(isset($this->merge['button']['header_actions'])?$this->merge['button']['header_actions']:'').'" /></td>
        </tr>
        <tr>
          <td>Tools text(with selected) </td>
          <td><input name="button[tools_copy]" type="text" id="button[tools_copy]" value="'.(isset($this->merge['button']['tools_copy'])?$this->merge['button']['tools_copy']:'').'" /></td>
        </tr>
        <tr>
          <td bgcolor="#eeeeee"><strong>Items</strong></td>
          <td bgcolor="#eeeeee">&nbsp;</td>
        </tr>
        <tr>
          <td width="21%">Add new item</td>
          <td width="79%"><input name="button[new_item]" type="text" id="button[new_item]" value="'.(isset($this->merge['button']['new_item'])?$this->merge['button']['new_item']:'').'" /></td>
        </tr>
        <tr>
          <td>Edit item </td>
          <td><input name="button[edit_item]" type="text" id="button[edit_item]" value="'.(isset($this->merge['button']['edit_item'])?$this->merge['button']['edit_item']:'').'" /></td>
        </tr>
        <tr>
          <td>Delete item </td>
          <td><input name="button[delete_item]" type="text" id="button[delete_item]" value="'.(isset($this->merge['button']['delete_item'])?$this->merge['button']['delete_item']:'').'" /></td>
        </tr>
        <tr>
          <td>Move item </td>
          <td><input name="button[move_item]" type="text" id="button[move_item]" value="'.(isset($this->merge['button']['move_item'])?$this->merge['button']['move_item']:'').'" /></td>
        </tr>
        <tr>
          <td>Activate item </td>
          <td><input name="button[active_item]" type="text" id="button[active_item]" value="'.(isset($this->merge['button']['active_item'])?$this->merge['button']['active_item']:'').'" /></td>
        </tr>
        <tr>
          <td>inActivate item </td>
          <td><input name="button[inactive_item]" type="text" id="button[inactive_item]" value="'.(isset($this->merge['button']['inactive_item'])?$this->merge['button']['inactive_item']:'').'" /></td>
        </tr>
        <tr>
          <td>Status  item hover </td>
          <td><input name="button[status_hover_item]" type="text" id="button[status_hover_item]" value="'.(isset($this->merge['button']['status_hover_item'])?$this->merge['button']['status_hover_item']:'').'" /></td>
        </tr>
        <tr>
          <td bgcolor="#eeeeee"><strong>Category</strong></td>
          <td bgcolor="#eeeeee">&nbsp;</td>
        </tr>
        <tr>
          <td>Add new category</td>
          <td><input name="button[new_category]" type="text" id="button[new_category]" value="'.(isset($this->merge['button']['new_category'])?$this->merge['button']['new_category']:'').'" /></td>
        </tr>
        <tr>
          <td>Edit category </td>
          <td><input name="button[edit_category]" type="text" id="button[edit_category]" value="'.(isset($this->merge['button']['edit_category'])?$this->merge['button']['edit_category']:'').'" /></td>
        </tr>
        <tr>
          <td>Delete category </td>
          <td><input name="button[delete_category]" type="text" id="button[delete_category]" value="'.(isset($this->merge['button']['delete_category'])?$this->merge['button']['delete_category']:'').'" /></td>
        </tr>
        <tr>
          <td>New sub category </td>
          <td><input name="button[new_subcategory]" type="text" id="button[new_subcategory]" value="'.(isset($this->merge['button']['new_subcategory'])?$this->merge['button']['new_subcategory']:'').'" /></td>
        </tr>
        <tr>
          <td>Status category hover </td>
          <td><input name="button[status_hover_cat]" type="text" id="button[status_hover_cat]" value="'.(isset($this->merge['button']['status_hover_cat'])?$this->merge['button']['status_hover_cat']:'').'" /></td>
        </tr>
      </table></td>
    </tr>
      <tr>
        <td bgcolor="#CCCCCC">Main content </td>
        <td bgcolor="#CCCCCC">&nbsp;</td>
      </tr>
      <tr>
        <td>Extra order </td>
        <td><input name="extra_sort" type="text" id="extra_sort" value="'.(isset($this->_data["."][0]['extra_sort'])?$this->_data["."][0]['extra_sort']:'').'" /></td>
      </tr>
      <tr>
        <td>Enable input date </td>
        <td><input name="act[]" type="checkbox" class="no_width" id="act[]" value="enable_date" '.(isset($this->_data["."][0]['enable_date_checked'])?$this->_data["."][0]['enable_date_checked']:'').' /></td>
      </tr>
	  
	  <tr>
    <td valign="top">Show main fields </td>
	
    <td>
	<p><a href="?mod=configure&act=addfield&tbl=content" class="divbox">New field</a></p>
	<table width="100%" border="0" cellspacing="1" cellpadding="1">
      <tr>
        <td width="16%" bgcolor="#eeeeee">Field</td>
        <td width="7%" bgcolor="#eeeeee">Name</td>
        <td width="23%" bgcolor="#eeeeee">Type</td>
        <td width="7%" bgcolor="#eeeeee">Require</td>
        <td width="10%" bgcolor="#eeeeee">Description</td>
        <td width="27%" bgcolor="#eeeeee">Require message </td>
        <td width="10%" bgcolor="#eeeeee">Sort order </td>
      </tr>
	  ';if(isset($this->_data['main_field.'])){for($i=0;$i< count($this->_data['main_field.']);$i++){$_tpl .= '
      <tr>
        <td><input type="checkbox" name="main_fields['.(isset($this->_data["main_field."][$i]["code"])?$this->_data["main_field."][$i]["code"]:'').'][chose]" '.(isset($this->_data["main_field."][$i]["chose_checked"])?$this->_data["main_field."][$i]["chose_checked"]:'').' value="1" />
          '.(isset($this->_data["main_field."][$i]["code"])?$this->_data["main_field."][$i]["code"]:'').'</td>
        <td><input name="main_fields['.(isset($this->_data["main_field."][$i]["code"])?$this->_data["main_field."][$i]["code"]:'').'][name]" type="text" size="8" value="'.(isset($this->_data["main_field."][$i]["name"])?$this->_data["main_field."][$i]["name"]:'').'"/></td>
        <td>'.(isset($this->_data["main_field."][$i]["type"])?$this->_data["main_field."][$i]["type"]:'').'     
		<p class="info '.(isset($this->_data["main_field."][$i]["cls_status"])?$this->_data["main_field."][$i]["cls_status"]:'').'">
		Default status: '.(isset($this->_data["main_field."][$i]["status_default"])?$this->_data["main_field."][$i]["status_default"]:'').'<br />
		Allow activate: <input name="main_fields['.(isset($this->_data["main_field."][$i]["code"])?$this->_data["main_field."][$i]["code"]:'').'][number]" type="text" size="8" value="'.(isset($this->_data["main_field."][$i]["number"])?$this->_data["main_field."][$i]["number"]:'').'" class="number" /></p>		</td>
        <td><input type="checkbox" name="main_fields['.(isset($this->_data["main_field."][$i]["code"])?$this->_data["main_field."][$i]["code"]:'').'][require]" value="1" '.(isset($this->_data["main_field."][$i]["require_checked"])?$this->_data["main_field."][$i]["require_checked"]:'').' /></td>
        <td><input name="main_fields['.(isset($this->_data["main_field."][$i]["code"])?$this->_data["main_field."][$i]["code"]:'').'][description]" type="text" size="8" value="'.(isset($this->_data["main_field."][$i]["description"])?$this->_data["main_field."][$i]["description"]:'').'" /></td>
        <td><input name="main_fields['.(isset($this->_data["main_field."][$i]["code"])?$this->_data["main_field."][$i]["code"]:'').'][require_msg]" type="text" size="10" value="'.(isset($this->_data["main_field."][$i]["require_msg"])?$this->_data["main_field."][$i]["require_msg"]:'').'" /></td>
        <td><input name="main_fields['.(isset($this->_data["main_field."][$i]["code"])?$this->_data["main_field."][$i]["code"]:'').'][sortorder]" type="text" size="10" value="'.(isset($this->_data["main_field."][$i]["sortorder"])?$this->_data["main_field."][$i]["sortorder"]:'').'" /></td>
      </tr>';}}$_tpl .= '
    </table>	</td>
  </tr>
  <tr>
    <td valign="top">Show language fields </td>
    <td>
	<p><a href="?mod=configure&act=addfield&tbl=content_ln" class="divbox">New field</a></p>
	<table width="100%" border="0" cellspacing="1" cellpadding="1">
      <tr>
        <td width="13%" bgcolor="#eeeeee">Field</td>
        <td width="7%" bgcolor="#eeeeee">Name</td>
        <td width="13%" bgcolor="#eeeeee">Type</td>
        <td width="7%" bgcolor="#eeeeee">Require</td>
        <td width="20%" bgcolor="#eeeeee">Description</td>
        <td width="29%" bgcolor="#eeeeee">Require message </td>
        <td width="11%" bgcolor="#eeeeee">Sort order </td>
      </tr>
	  ';if(isset($this->_data['ln_field.'])){for($i=0;$i< count($this->_data['ln_field.']);$i++){$_tpl .= '
      <tr>
        <td><input type="checkbox" name="ln_fields['.(isset($this->_data["ln_field."][$i]["code"])?$this->_data["ln_field."][$i]["code"]:'').'][chose]" '.(isset($this->_data["ln_field."][$i]["chose_checked"])?$this->_data["ln_field."][$i]["chose_checked"]:'').' value="1" />
          '.(isset($this->_data["ln_field."][$i]["code"])?$this->_data["ln_field."][$i]["code"]:'').'</td>
        <td><input name="ln_fields['.(isset($this->_data["ln_field."][$i]["code"])?$this->_data["ln_field."][$i]["code"]:'').'][name]" type="text" size="8" value="'.(isset($this->_data["ln_field."][$i]["name"])?$this->_data["ln_field."][$i]["name"]:'').'"/></td>
        <td>'.(isset($this->_data["ln_field."][$i]["type"])?$this->_data["ln_field."][$i]["type"]:'').'</td>
        <td><input type="checkbox" name="ln_fields['.(isset($this->_data["ln_field."][$i]["code"])?$this->_data["ln_field."][$i]["code"]:'').'][require]" value="1" '.(isset($this->_data["ln_field."][$i]["require_checked"])?$this->_data["ln_field."][$i]["require_checked"]:'').' /></td>
        <td><input name="ln_fields['.(isset($this->_data["ln_field."][$i]["code"])?$this->_data["ln_field."][$i]["code"]:'').'][description]" type="text" size="8" value="'.(isset($this->_data["ln_field."][$i]["description"])?$this->_data["ln_field."][$i]["description"]:'').'" /></td>
        <td><input name="ln_fields['.(isset($this->_data["ln_field."][$i]["code"])?$this->_data["ln_field."][$i]["code"]:'').'][require_msg]" type="text" size="10" value="'.(isset($this->_data["ln_field."][$i]["require_msg"])?$this->_data["ln_field."][$i]["require_msg"]:'').'" /></td>
        <td><input name="ln_fields['.(isset($this->_data["ln_field."][$i]["code"])?$this->_data["ln_field."][$i]["code"]:'').'][sortorder]" type="text" size="10" value="'.(isset($this->_data["ln_field."][$i]["sortorder"])?$this->_data["ln_field."][$i]["sortorder"]:'').'" /></td>
      </tr>';}}$_tpl .= '
    </table>
     </td>
  </tr>
      <tr>
        <td>Options</td>
        <td>
		  <table width="100%" border="0" cellspacing="1" cellpadding="1">
            <tr>
              <td width="20%" bgcolor="#eeeeee">Options</td>
              <td width="32%" bgcolor="#eeeeee">Type</td>
              <td width="48%" bgcolor="#eeeeee">Special save field </td>
            </tr>
			';if(isset($this->_data['options.'])){for($i=0;$i< count($this->_data['options.']);$i++){$_tpl .= '
            <tr>
              <td><input name="options[]" class="no_width" type="checkbox" id="options[]" value="'.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').'" '.(isset($this->_data["options."][$i]["checked"])?$this->_data["options."][$i]["checked"]:'').' /> '.(isset($this->_data["options."][$i]["name"])?$this->_data["options."][$i]["name"]:'').'</td>
              <td><select name="options_type['.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').']">
            <option value="0" '.(isset($this->_data["options."][$i]["selected_0"])?$this->_data["options."][$i]["selected_0"]:'').'>Radio</option>
            <option value="1" '.(isset($this->_data["options."][$i]["selected_1"])?$this->_data["options."][$i]["selected_1"]:'').'>Checkbox</option>
            <option value="2" '.(isset($this->_data["options."][$i]["selected_2"])?$this->_data["options."][$i]["selected_2"]:'').'>Dropdown</option>
            <option value="3" '.(isset($this->_data["options."][$i]["selected_3"])?$this->_data["options."][$i]["selected_3"]:'').'>Dropdown with multi select</option>
          </select></td>
              <td><input type="text" name="options_save_field['.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').']" value="'.(isset($this->_data["options."][$i]["options_save_field"])?$this->_data["options."][$i]["options_save_field"]:'').'" /></td>
            </tr>
			';}}$_tpl .= ' 
          </table>        </td>
      </tr>
      <tr>
        <td>Extra Files </td>
        <td><table width="666" border="0" cellpadding="1" cellspacing="1" id="file_extra">
          <tr>
            <td width="144" bgcolor="#eeeeee">Name <a href="#" title="Leave a blank for any extension ">?</a></td>
            <td width="39" bgcolor="#eeeeee">Code</td>
            <td width="249" bgcolor="#eeeeee">File type <a href="#" title="Leave a blank for any extension ">?</a> </td>
            <td width="221" bgcolor="#eeeeee">Note</td>
          </tr>
		  ';if(isset($this->_data['file_extra.'])){for($i=0;$i< count($this->_data['file_extra.']);$i++){$_tpl .= '
          <tr>
            <td><input type="text" name="file_extra[name][]" value="'.(isset($this->_data["file_extra."][$i]["name"])?$this->_data["file_extra."][$i]["name"]:'').'" /></td>
            <td><input name="file_extra[code][]" type="text" id="file_extra[code][]" value="'.(isset($this->_data["file_extra."][$i]["code"])?$this->_data["file_extra."][$i]["code"]:'').'" size="5" /></td>
            <td><input type="text" name="file_extra[type][]" value="'.(isset($this->_data["file_extra."][$i]["type"])?$this->_data["file_extra."][$i]["type"]:'').'" /></td>
            <td><input type="text" name="file_extra[note][]" value="'.(isset($this->_data["file_extra."][$i]["note"])?$this->_data["file_extra."][$i]["note"]:'').'" /><a href="#" onclick="delete_row(this);return false;"> x </a></td>
          </tr>
          ';}}$_tpl .= '
        </table>
		<a href="#" onclick="add_file_extra(); return false;">Add</a>		</td>
      </tr>
	  <tr>
        <td>Extra general fields </td>
        <td><table width="666" border="0" cellpadding="1" cellspacing="1" id="fields_extra">
          <tr>
            <td width="144" bgcolor="#eeeeee">Name <a href="#" title="Leave a blank for any extension ">?</a></td>
            <td width="39" bgcolor="#eeeeee">Code</td>
            <td width="249" bgcolor="#eeeeee">File type <a href="#" title="Leave a blank for any extension ">?</a> </td>
            <td width="221" bgcolor="#eeeeee">Note</td>
          </tr>
		  ';if(isset($this->_data['fields_extra.'])){for($i=0;$i< count($this->_data['fields_extra.']);$i++){$_tpl .= '
          <tr>
            <td><input type="text" name="fields_extra[name][]" value="'.(isset($this->_data["fields_extra."][$i]["name"])?$this->_data["fields_extra."][$i]["name"]:'').'" /></td>
            <td><input name="fields_extra[code][]" type="text" id="fields_extra[code][]" value="'.(isset($this->_data["fields_extra."][$i]["code"])?$this->_data["fields_extra."][$i]["code"]:'').'" size="5" /></td>
            <td>'.(isset($this->_data["fields_extra."][$i]["type"])?$this->_data["fields_extra."][$i]["type"]:'').'</td>
            <td><input type="text" name="fields_extra[note][]" value="'.(isset($this->_data["fields_extra."][$i]["note"])?$this->_data["fields_extra."][$i]["note"]:'').'" /><a href="#" onclick="delete_row(this);return false;"> x </a></td>
          </tr>
          ';}}$_tpl .= '
        </table>
		<a href="#" onclick="add_fields_extra(); return false;">Add</a>		</td>
      </tr>
	  <tr>
        <td>Extra language fields </td>
        <td><table width="666" border="0" cellpadding="1" cellspacing="1" id="ln_fields_extra">
          <tr>
            <td width="144" bgcolor="#eeeeee">Name <a href="#" title="Leave a blank for any extension ">?</a></td>
            <td width="39" bgcolor="#eeeeee">Code</td>
            <td width="249" bgcolor="#eeeeee">File type <a href="#" title="Leave a blank for any extension ">?</a> </td>
            <td width="221" bgcolor="#eeeeee">Note</td>
          </tr>
		  ';if(isset($this->_data['ln_fields_extra.'])){for($i=0;$i< count($this->_data['ln_fields_extra.']);$i++){$_tpl .= '
          <tr>
            <td><input type="text" name="ln_fields_extra[name][]" value="'.(isset($this->_data["ln_fields_extra."][$i]["name"])?$this->_data["ln_fields_extra."][$i]["name"]:'').'" /></td>
            <td><input name="ln_fields_extra[code][]" type="text" id="ln_fields_extra[code][]" value="'.(isset($this->_data["ln_fields_extra."][$i]["code"])?$this->_data["ln_fields_extra."][$i]["code"]:'').'" size="5" /></td>
            <td>'.(isset($this->_data["ln_fields_extra."][$i]["type"])?$this->_data["ln_fields_extra."][$i]["type"]:'').'</td>
            <td><input type="text" name="ln_fields_extra[note][]" value="'.(isset($this->_data["ln_fields_extra."][$i]["note"])?$this->_data["ln_fields_extra."][$i]["note"]:'').'" /><a href="#" onclick="delete_row(this);return false;"> x </a></td>
          </tr>
          ';}}$_tpl .= '
        </table>
		<a href="#" onclick="add_ln_fields_extra(); return false;">Add</a>		</td>
      </tr>
  </table>
    <table width="100%" border="0" cellspacing="0" cellpadding="2" class="table-Form1 table_list">
  <tr>
    <td valign="top">View template </td>
    <td><input name="tpl_view" type="text" id="tpl_view" value="'.(isset($this->_data["."][0]['tpl_view'])?$this->_data["."][0]['tpl_view']:'').'" /></td>
  </tr>
  <tr>
    <td valign="top">Update template </td>
    <td><input name="tpl_update" type="text" id="tpl_update" value="'.(isset($this->_data["."][0]['tpl_update'])?$this->_data["."][0]['tpl_update']:'').'" /></td>
  </tr>
  <tr>
    <td valign="top">Rows per page </td>
    <td><input name="rows_per_page" type="text" id="rows_per_page" value="'.(isset($this->_data["."][0]['rows_per_page'])?$this->_data["."][0]['rows_per_page']:'').'" /></td>
  </tr>
  <tr>
    <td valign="top">&nbsp;</td>
    <td><input name="act[]" type="checkbox" class="no_width" id="act[]" value="drapdrop_content" '.(isset($this->_data["."][0]['drapdrop_content_checked'])?$this->_data["."][0]['drapdrop_content_checked']:'').' />
      Enable drap-n-drop content </td>
  </tr>
  <tr>
    <td valign="top" width="200">Actions</td>
    <td>
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="new" '.(isset($this->_data["."][0]['new_checked'])?$this->_data["."][0]['new_checked']:'').'>
    New <br>
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="update" '.(isset($this->_data["."][0]['update_checked'])?$this->_data["."][0]['update_checked']:'').'>
    Edit <br>
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="delete" '.(isset($this->_data["."][0]['delete_checked'])?$this->_data["."][0]['delete_checked']:'').'>
    Delete <br>
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="comment" '.(isset($this->_data["."][0]['comment_checked'])?$this->_data["."][0]['comment_checked']:'').'>
    Manage Comment     
    <input name="comment_name" type="text" id="comment_name" value="'.(isset($this->_data["."][0]['comment_name'])?$this->_data["."][0]['comment_name']:'').'" />
    <br />
  
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="move" '.(isset($this->_data["."][0]['move_checked'])?$this->_data["."][0]['move_checked']:'').'>
   Move to category	<br />
<input name="act[]" type="checkbox" class="no_width" id="act[]" value="featuredon" '.(isset($this->_data["."][0]['featuredon_checked'])?$this->_data["."][0]['featuredon_checked']:'').'>
   Featured on    
   <input name="featuredon_name" type="text" id="featuredon_name" value="'.(isset($this->_data["."][0]['featuredon_name'])?$this->_data["."][0]['featuredon_name']:'').'" />
   <br /></td>
  </tr>
  <tr>
    <td valign="top">No delete product Ids </td>
    <td><input name="nodel_ids" type="text" id="nodel_ids" value="'.(isset($this->_data["."][0]['nodel_ids'])?$this->_data["."][0]['nodel_ids']:'').'" /></td>
  </tr>
  <tr>
    <td valign="top">Thumb view </td>
    <td><input name="thumb_field" type="text" id="thumb_field" value="'.(isset($this->_data["."][0]['thumb_field'])?$this->_data["."][0]['thumb_field']:'').'" /></td>
  </tr>
  <tr>
    <td valign="top">Fields on list </td>
    <td><input name="list_field" type="text" id="list_field" value="'.(isset($this->_data["."][0]['list_field'])?$this->_data["."][0]['list_field']:'').'" />&nbsp;</td>
  </tr>
  
  <tr>
    <td valign="top">And Order </td>
    <td><input name="sort_order" type="text" id="sort_order" value="'.(isset($this->_data["."][0]['sort_order'])?$this->_data["."][0]['sort_order']:'').'" /></td>
  </tr>
  <tr>
    <td valign="top"><h4><input name="act[]" type="checkbox" class="no_width" id="act[]" value="image" '.(isset($this->_data["."][0]['image_checked'])?$this->_data["."][0]['image_checked']:'').'> 
      Main Image</h4></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td width="200"><input name="main_icon[chose]" type="checkbox" class="no_width" id="main_icon[chose]" value="1" '.(isset($this->_data["."][0]['main_icon_chose'])?$this->_data["."][0]['main_icon_chose']:'').'>
      Icon</td>
    <td> 
      
	  Resize <input name="main_icon[w]" type="text" class="no_width" id="main_icon[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['main_icon_w'])?$this->_data["."][0]['main_icon_w']:'').'">
      x
      
      <input name="main_icon[h]" type="text" class="no_width" id="main_icon[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['main_icon_h'])?$this->_data["."][0]['main_icon_h']:'').'">
	  File name 
	  <input name="main_icon[name]" type="text" class="no_width" id="main_icon[name]" value="'.(isset($this->_data["."][0]['main_icon_name'])?$this->_data["."][0]['main_icon_name']:'').'" />
	  
<div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="main_icon[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['main_icon_force_resize_true'])?$this->_data["."][0]['main_icon_force_resize_true']:'').' />
Force resize
  <input name="main_icon[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['main_icon_force_resize_false'])?$this->_data["."][0]['main_icon_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="main_icon[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['main_icon_specify_none'])?$this->_data["."][0]['main_icon_specify_none']:'').' />
      None
      <input name="main_icon[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['main_icon_specify_min'])?$this->_data["."][0]['main_icon_specify_min']:'').' />
Min 
  <input name="main_icon[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['main_icon_specify_max'])?$this->_data["."][0]['main_icon_specify_max']:'').' />
Max </td>
    <td><input name="main_icon[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['main_icon_orginal_0'])?$this->_data["."][0]['main_icon_orginal_0']:'').' />
No 
  <input name="main_icon[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['main_icon_orginal_1'])?$this->_data["."][0]['main_icon_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>
</div>	

  </td>
  </tr>
  <tr>
    <td><input name="main_img[chose]" type="checkbox" class="no_width" id="main_img[chose]" value="1" '.(isset($this->_data["."][0]['main_img_chose'])?$this->_data["."][0]['main_img_chose']:'').'>
      Image</td>
    <td>
	
	Resize <input name="main_img[w]" type="text" class="no_width" id="main_img[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['main_img_w'])?$this->_data["."][0]['main_img_w']:'').'">
      x
      <input name="main_img[h]" type="text" class="no_width" id="main_img[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['main_img_h'])?$this->_data["."][0]['main_img_h']:'').'"> File name:<input name="main_img[name]" type="text" class="no_width" id="main_img[name]"  value="'.(isset($this->_data["."][0]['main_img_name'])?$this->_data["."][0]['main_img_name']:'').'">
<div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
	
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="main_img[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['main_img_force_resize_true'])?$this->_data["."][0]['main_img_force_resize_true']:'').' />
Force resize
  <input name="main_img[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['main_img_force_resize_false'])?$this->_data["."][0]['main_img_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="main_img[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['main_img_specify_none'])?$this->_data["."][0]['main_img_specify_none']:'').' />
      None
      <input name="main_img[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['main_img_specify_min'])?$this->_data["."][0]['main_img_specify_min']:'').' />
Min 
  <input name="main_img[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['main_img_specify_max'])?$this->_data["."][0]['main_img_specify_max']:'').' />
Max </td>
    <td><input name="main_img[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['main_img_orginal_0'])?$this->_data["."][0]['main_img_orginal_0']:'').' />
No 
  <input name="main_img[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['main_img_orginal_1'])?$this->_data["."][0]['main_img_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>

</div>	  	  </td>
  </tr>
  <tr>
    <td><input name="main_thumb[chose]" type="checkbox" class="no_width" id="main_thumb[chose]" value="1" '.(isset($this->_data["."][0]['main_thumb_chose'])?$this->_data["."][0]['main_thumb_chose']:'').'>
      Image Thumb </td>
    <td>
Resize <input name="main_thumb[w]" type="text" class="no_width" id="main_thumb[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['main_thumb_w'])?$this->_data["."][0]['main_thumb_w']:'').'">
      x
      <input name="main_thumb[h]" type="text" class="no_width" id="main_thumb[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['main_thumb_h'])?$this->_data["."][0]['main_thumb_h']:'').'">
<div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="23%" bgcolor="#eeeeee">Method</td>
    <td width="40%" bgcolor="#eeeeee">Specify</td>
    <td width="19%" bgcolor="#eeeeee">&nbsp;</td>
  </tr>
  <tr>
    <td><input name="main_thumb[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['main_thumb_force_resize_true'])?$this->_data["."][0]['main_thumb_force_resize_true']:'').' />
Force resize
  <input name="main_thumb[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['main_thumb_force_resize_false'])?$this->_data["."][0]['main_thumb_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="main_thumb[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['main_thumb_specify_none'])?$this->_data["."][0]['main_thumb_specify_none']:'').' />
      None
      <input name="main_thumb[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['main_thumb_specify_min'])?$this->_data["."][0]['main_thumb_specify_min']:'').' />
Min 
  <input name="main_thumb[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['main_thumb_specify_max'])?$this->_data["."][0]['main_thumb_specify_max']:'').' />
Max </td>
    <td>&nbsp;</td>
  </tr>
</table>
</div>	  </td>
  </tr>
  <tr>
    <td valign="top"><h4><input name="act[]" type="checkbox" class="no_width" id="act[]" value="ln_image" '.(isset($this->_data["."][0]['ln_image_checked'])?$this->_data["."][0]['ln_image_checked']:'').'> 
      Languages Image</h4></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td width="200"><input name="ln_main_icon[chose]" type="checkbox" class="no_width" id="ln_main_icon[chose]" value="1" '.(isset($this->_data["."][0]['ln_main_icon_chose'])?$this->_data["."][0]['ln_main_icon_chose']:'').'>
      Icon</td>
    <td>
Resize <input name="ln_main_icon[w]" type="text" class="no_width" id="ln_main_icon[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_main_icon_w'])?$this->_data["."][0]['ln_main_icon_w']:'').'">
      x
      
      <input name="ln_main_icon[h]" type="text" class="no_width" id="ln_main_icon[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_main_icon_h'])?$this->_data["."][0]['ln_main_icon_h']:'').'"> File name: 	<input name="ln_main_icon[name]" type="text" class="no_width" id="ln_main_icon[name]"  value="'.(isset($this->_data["."][0]['ln_main_icon_name'])?$this->_data["."][0]['ln_main_icon_name']:'').'">
<div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
      
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="ln_main_icon[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['ln_main_icon_force_resize_true'])?$this->_data["."][0]['ln_main_icon_force_resize_true']:'').' />
Force resize
  <input name="ln_main_icon[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['ln_main_icon_force_resize_false'])?$this->_data["."][0]['ln_main_icon_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="ln_main_icon[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['ln_main_icon_specify_none'])?$this->_data["."][0]['ln_main_icon_specify_none']:'').' />
      None
      <input name="ln_main_icon[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['ln_main_icon_specify_min'])?$this->_data["."][0]['ln_main_icon_specify_min']:'').' />
Min 
  <input name="ln_main_icon[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['ln_main_icon_specify_max'])?$this->_data["."][0]['ln_main_icon_specify_max']:'').' />
Max </td>
    <td><input name="ln_main_icon[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['ln_main_icon_orginal_0'])?$this->_data["."][0]['ln_main_icon_orginal_0']:'').' />
No 
  <input name="ln_main_icon[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['ln_main_icon_orginal_1'])?$this->_data["."][0]['ln_main_icon_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>
</div>	 </td>
  </tr>
  <tr>
    <td><input name="ln_main_img[chose]" type="checkbox" class="no_width" id="ln_main_img[chose]" value="1" '.(isset($this->_data["."][0]['ln_main_img_chose'])?$this->_data["."][0]['ln_main_img_chose']:'').'>
      Image</td>
    <td>
	Resize <input name="ln_main_img[w]" type="text" class="no_width" id="ln_main_img[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_main_img_w'])?$this->_data["."][0]['ln_main_img_w']:'').'">
      x
      <input name="ln_main_img[h]" type="text" class="no_width" id="ln_main_img[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_main_img_h'])?$this->_data["."][0]['ln_main_img_h']:'').'"> File name: <input name="ln_main_img[name]" type="text" class="no_width" id="ln_main_img[name]"  value="'.(isset($this->_data["."][0]['ln_main_img_name'])?$this->_data["."][0]['ln_main_img_name']:'').'">
<div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="ln_main_img[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['ln_main_img_force_resize_true'])?$this->_data["."][0]['ln_main_img_force_resize_true']:'').' />
Force resize
  <input name="ln_main_img[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['ln_main_img_force_resize_false'])?$this->_data["."][0]['ln_main_img_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="ln_main_img[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['ln_main_img_specify_none'])?$this->_data["."][0]['ln_main_img_specify_none']:'').' />
      None
      <input name="ln_main_img[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['ln_main_img_specify_min'])?$this->_data["."][0]['ln_main_img_specify_min']:'').' />
Min 
  <input name="ln_main_img[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['ln_main_img_specify_max'])?$this->_data["."][0]['ln_main_img_specify_max']:'').' />
Max </td>
    <td><input name="ln_main_img[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['ln_main_img_orginal_0'])?$this->_data["."][0]['ln_main_img_orginal_0']:'').' />
No 
  <input name="ln_main_img[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['ln_main_img_orginal_1'])?$this->_data["."][0]['ln_main_img_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>
</div>	</td>
  </tr>
  <tr>
    <td><input name="ln_main_thumb[chose]" type="checkbox" class="no_width" id="ln_main_thumb[chose]" value="1" '.(isset($this->_data["."][0]['ln_main_thumb_chose'])?$this->_data["."][0]['ln_main_thumb_chose']:'').'>
      Image Thumb </td>
    <td>
	Resize <input name="ln_main_thumb[w]" type="text" class="no_width" id="ln_main_thumb[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_main_thumb_w'])?$this->_data["."][0]['ln_main_thumb_w']:'').'">
      x
      <input name="ln_main_thumb[h]" type="text" class="no_width" id="ln_main_thumb[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_main_thumb_h'])?$this->_data["."][0]['ln_main_thumb_h']:'').'">
	<div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>

	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="23%" bgcolor="#eeeeee">Method</td>
    <td width="40%" bgcolor="#eeeeee">Specify</td>
    <td width="19%" bgcolor="#eeeeee">&nbsp;</td>
  </tr>
  <tr>
    <td><input name="ln_main_thumb[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['ln_main_thumb_force_resize_true'])?$this->_data["."][0]['ln_main_thumb_force_resize_true']:'').' />
Force resize
  <input name="ln_main_thumb[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['ln_main_thumb_force_resize_false'])?$this->_data["."][0]['ln_main_thumb_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="ln_main_thumb[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['ln_main_thumb_specify_none'])?$this->_data["."][0]['ln_main_thumb_specify_none']:'').' />
      None
      <input name="ln_main_thumb[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['ln_main_thumb_specify_min'])?$this->_data["."][0]['ln_main_thumb_specify_min']:'').' />
Min 
  <input name="ln_main_thumb[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['ln_main_thumb_specify_max'])?$this->_data["."][0]['ln_main_thumb_specify_max']:'').' />
Max </td>
    <td>&nbsp;</td>
  </tr>
</table>
	</div>	</td>
  </tr>

  <tr>
    <td> <h4><input name="act[]" type="checkbox" class="no_width" id="act[]" value="gallery" '.(isset($this->_data["."][0]['gallery_checked'])?$this->_data["."][0]['gallery_checked']:'').'> 
      Gallery Image </h4></td>
    <td><input name="act[]" type="checkbox" class="no_width" id="act[]" value="drapdrop_gallery" '.(isset($this->_data["."][0]['drapdrop_gallery_checked'])?$this->_data["."][0]['drapdrop_gallery_checked']:'').' /> Enable drap-n-drop gallery&nbsp;<br />
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="multiselect_file_gallery" '.(isset($this->_data["."][0]['multiselect_file_gallery_checked'])?$this->_data["."][0]['multiselect_file_gallery_checked']:'').' /> Multi select file (only Firefox, also only enable this option when gallery is not include title or icon)<br />
      Gallery name: 
      <input name="gallery_name" type="text" id="gallery_name" value="'.(isset($this->_data["."][0]['gallery_name'])?$this->_data["."][0]['gallery_name']:'').'" /></td>
  </tr>
  <tr>
    <td>Order by </td>
    <td>order_id AND      
      <select name="gallery_sort" id="gallery_sort">
        <option value="id ASC">Id ASC</option>
        <option value="id DESC">Id DESC</option>
      </select></td>
  </tr>
  <tr>
    <td>Show fields </td>
    <td><input name="gallery_fields" type="text" id="gallery_fields" value="'.(isset($this->_data["."][0]['gallery_fields'])?$this->_data["."][0]['gallery_fields']:'').'" /></td>
  </tr>
  <tr>
    <td width="200"><input name="gallery_icon[chose]" type="checkbox" class="no_width" id="gallery_icon[chose]" value="1" '.(isset($this->_data["."][0]['gallery_icon_chose'])?$this->_data["."][0]['gallery_icon_chose']:'').'>
      Icon</td>
    <td>
	Resize <input name="gallery_icon[w]" type="text" class="no_width" id="gallery_icon[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['gallery_icon_w'])?$this->_data["."][0]['gallery_icon_w']:'').'" />
x
<input name="gallery_icon[h]" type="text" class="no_width" id="gallery_icon[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['gallery_icon_h'])?$this->_data["."][0]['gallery_icon_h']:'').'" /> File name: <input name="gallery_icon[name]" type="text" class="no_width" id="gallery_icon[name]" value="'.(isset($this->_data["."][0]['gallery_icon_name'])?$this->_data["."][0]['gallery_icon_name']:'').'" />
	<div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
	
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="gallery_icon[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['gallery_icon_force_resize_true'])?$this->_data["."][0]['gallery_icon_force_resize_true']:'').' />
Force resize
  <input name="gallery_icon[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['gallery_icon_force_resize_false'])?$this->_data["."][0]['gallery_icon_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="gallery_icon[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['gallery_icon_specify_none'])?$this->_data["."][0]['gallery_icon_specify_none']:'').' />
      None
      <input name="gallery_icon[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['gallery_icon_specify_min'])?$this->_data["."][0]['gallery_icon_specify_min']:'').' />
Min 
  <input name="gallery_icon[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['gallery_icon_specify_max'])?$this->_data["."][0]['gallery_icon_specify_max']:'').' />
Max </td>
    <td><input name="gallery_icon[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['gallery_icon_orginal_0'])?$this->_data["."][0]['gallery_icon_orginal_0']:'').' />
No 
  <input name="gallery_icon[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['gallery_icon_orginal_1'])?$this->_data["."][0]['gallery_icon_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>
	</div>	</td>
  </tr>
  <tr>
    <td><input name="gallery_img[chose]" type="checkbox" class="no_width" id="gallery_img[chose]" value="1" checked="checked" style="display: none;">
      Image</td>
    <td>
	
	Resize <input name="gallery_img[w]" type="text" class="no_width" id="gallery_img[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['gallery_img_w'])?$this->_data["."][0]['gallery_img_w']:'').'">
      x
      <input name="gallery_img[h]" type="text" class="no_width" id="gallery_img[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['gallery_img_h'])?$this->_data["."][0]['gallery_img_h']:'').'"> File name: <input name="gallery_img[name]" type="text" class="no_width" id="gallery_img[name]" value="'.(isset($this->_data["."][0]['gallery_img_name'])?$this->_data["."][0]['gallery_img_name']:'').'" />
		<div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>

	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="gallery_img[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['gallery_img_force_resize_true'])?$this->_data["."][0]['gallery_img_force_resize_true']:'').' />
Force resize
  <input name="gallery_img[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['gallery_img_force_resize_false'])?$this->_data["."][0]['gallery_img_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="gallery_img[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['gallery_img_specify_none'])?$this->_data["."][0]['gallery_img_specify_none']:'').' />
      None
      <input name="gallery_img[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['gallery_img_specify_min'])?$this->_data["."][0]['gallery_img_specify_min']:'').' />
Min 
  <input name="gallery_img[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['gallery_img_specify_max'])?$this->_data["."][0]['gallery_img_specify_max']:'').' />
Max </td>
    <td><input name="gallery_img[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['gallery_img_orginal_0'])?$this->_data["."][0]['gallery_img_orginal_0']:'').' />
No 
  <input name="gallery_img[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['gallery_img_orginal_1'])?$this->_data["."][0]['gallery_img_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>
		</div>	</td>
  </tr>
  <tr>
    <td><input name="gallery_thumb[chose]" type="checkbox" class="no_width" id="gallery_thumb[chose]" value="1" '.(isset($this->_data["."][0]['gallery_thumb_chose'])?$this->_data["."][0]['gallery_thumb_chose']:'').'>
      Image Thumb </td>
    <td>
	Resize: <input name="gallery_thumb[w]" type="text" class="no_width" id="gallery_thumb[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['gallery_thumb_w'])?$this->_data["."][0]['gallery_thumb_w']:'').'">
      x
      <input name="gallery_thumb[h]" type="text" class="no_width" id="gallery_thumb[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['gallery_thumb_h'])?$this->_data["."][0]['gallery_thumb_h']:'').'">
		<div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="23%" bgcolor="#eeeeee">Method</td>
    <td width="40%" bgcolor="#eeeeee">Specify</td>
    <td width="19%" bgcolor="#eeeeee">&nbsp;</td>
  </tr>
  <tr>
    <td><input name="gallery_thumb[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['gallery_thumb_force_resize_true'])?$this->_data["."][0]['gallery_thumb_force_resize_true']:'').' />
Force resize
  <input name="gallery_thumb[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['gallery_thumb_force_resize_false'])?$this->_data["."][0]['gallery_thumb_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="gallery_thumb[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['gallery_thumb_specify_none'])?$this->_data["."][0]['gallery_thumb_specify_none']:'').' />
      None
      <input name="gallery_thumb[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['gallery_thumb_specify_min'])?$this->_data["."][0]['gallery_thumb_specify_min']:'').' />
Min 
  <input name="gallery_thumb[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['gallery_thumb_specify_max'])?$this->_data["."][0]['gallery_thumb_specify_max']:'').' />
Max </td>
    <td>&nbsp;</td>
  </tr>
</table>
		</div>	</td>
  </tr>
   <tr>
     <td bgcolor="#CCCCCC">Sub content </td>
     <td bgcolor="#CCCCCC">&nbsp;</td>
   </tr>
   <tr>
     <td>&nbsp;</td>
     <td><input type="checkbox" name="act[]" value="subcontent" '.(isset($this->_data["."][0]['subcontent_checked'])?$this->_data["."][0]['subcontent_checked']:'').' /> 
       Enable sub content 
       <input name="sub_name" type="text" id="sub_name" value="'.(isset($this->_data["."][0]['sub_name'])?$this->_data["."][0]['sub_name']:'').'" /></td>
   </tr>
   <tr>
     <td width="200">Show fields</td>
     <td width="78%"><input name="sub_show_fields" type="text" id="sub_show_fields" value="'.(isset($this->_data["."][0]['sub_show_fields'])?$this->_data["."][0]['sub_show_fields']:'').'" /></td>
   </tr>
 

   <tr>
     <td valign="top" bgcolor="#CCCCCC">Category</td>
     <td bgcolor="#CCCCCC">&nbsp;</td>
   </tr>
   <tr>
    <td width="200" valign="top">Actions</td>
    <td width="78%">	
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="newcat" '.(isset($this->_data["."][0]['newcat_checked'])?$this->_data["."][0]['newcat_checked']:'').'>
    New<br>
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="updatecat" '.(isset($this->_data["."][0]['updatecat_checked'])?$this->_data["."][0]['updatecat_checked']:'').'>
    Edit<br>
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="deletecat" '.(isset($this->_data["."][0]['deletecat_checked'])?$this->_data["."][0]['deletecat_checked']:'').'>
    Delete<br>
	<input name="act[]" type="checkbox" class="no_width" id="act[]" value="viewcat" '.(isset($this->_data["."][0]['viewcat_checked'])?$this->_data["."][0]['viewcat_checked']:'').'>
   View product in category<br />
   <input name="act[]" type="checkbox" class="no_width" id="act[]" value="drapdrop_cat" '.(isset($this->_data["."][0]['drapdrop_cat_checked'])?$this->_data["."][0]['drapdrop_cat_checked']:'').' /> Enable drap-n-drop category</td>
  </tr>
   <tr>
     <td valign="top">Template update </td>
     <td><input name="cattpl_update" type="text" id="cattpl_update" value="'.(isset($this->_data["."][0]['cattpl_update'])?$this->_data["."][0]['cattpl_update']:'').'" /></td>
   </tr>
   <tr>
    <td valign="top">Languages</td>
    <td><select name="cat_languages">
          <option value="0">All</option>
		  <option value="1" '.(isset($this->_data["."][0]['selected_cat_languages_1'])?$this->_data["."][0]['selected_cat_languages_1']:'').'>Default language</option>
        </select></td>
  </tr>
  <tr>
    <td valign="top">Max Level </td>
    <td> <input name="nlevel" type="text" class="no_width"  value="'.(isset($this->_data["."][0]['nlevel'])?$this->_data["."][0]['nlevel']:'').'" size="3"></td>
  </tr>
  <tr>
    <td valign="top">No new    product in level </td>
    <td><input name="noproduct_level" type="text" id="noproduct_level" value="'.(isset($this->_data["."][0]['noproduct_level'])?$this->_data["."][0]['noproduct_level']:'').'" /></td>
  </tr>
  <tr>
    <td valign="top">No new product in categorys </td>
    <td><input name="noproduct_cat" type="text" id="noproduct_cat" value="'.(isset($this->_data["."][0]['noproduct_cat'])?$this->_data["."][0]['noproduct_cat']:'').'" /></td>
  </tr>
  <tr>
    <td>No new category in levels</td>
    <td><input name="nosubcat_level" type="text" id="nosubcat_level" value="'.(isset($this->_data["."][0]['nosubcat_level'])?$this->_data["."][0]['nosubcat_level']:'').'" />
      <br />
      <input type="checkbox" class="no_width" name="nodelcat_level" value="1" '.(isset($this->_data["."][0]['nodelcat_level_checked'])?$this->_data["."][0]['nodelcat_level_checked']:'').' /> 
      Don\'t delete current subcategory </td>
  </tr>
  <tr>
    <td>No  new  category in categorys</td>
    <td><input name="nosubcat_cat" type="text" id="nosubcat_cat" value="'.(isset($this->_data["."][0]['nosubcat_cat'])?$this->_data["."][0]['nosubcat_cat']:'').'" />
      <br />
      <input type="checkbox" name="nodelcat_cat" class="no_width" value="1" '.(isset($this->_data["."][0]['nodelcat_cat_checked'])?$this->_data["."][0]['nodelcat_cat_checked']:'').' /> 
      Don\'t delete current subcategory </td>
  </tr>
  <tr>
    <td>No  delete category Ids </td>
    <td><input name="nodelcat_ids" type="text" id="nodelcat_ids" value="'.(isset($this->_data["."][0]['nodelcat_ids'])?$this->_data["."][0]['nodelcat_ids']:'').'" /></td>
  </tr>
  <tr>
    <td>Required fields </td>
    <td><input name="category_required" type="text" id="category_required" value="'.(isset($this->_data["."][0]['category_required'])?$this->_data["."][0]['category_required']:'').'" /></td>
  </tr>
  <tr>
    <td>Category fields on list </td>
    <td><input name="list_catfield" type="text" id="gallery_fields" value="'.(isset($this->_data["."][0]['list_catfield'])?$this->_data["."][0]['list_catfield']:'').'" /></td>
  </tr>
        <tr>
        <td>Enable input date </td>
        <td><input name="act[]" type="checkbox" class="no_width" id="act[]" value="enable_catdate" '.(isset($this->_data["."][0]['enable_catdate_checked'])?$this->_data["."][0]['enable_catdate_checked']:'').' /></td>
      </tr>

<tr>
    <td valign="top">Show main fields </td>
    <td>
	<p><a href="?mod=configure&act=addfield&tbl=category" class="divbox">New field</a></p>
	<table width="100%" border="0" cellspacing="1" cellpadding="1">
      <tr>
        <td width="17%" bgcolor="#eeeeee">Field</td>
        <td width="6%" bgcolor="#eeeeee">Name</td>
        <td width="14%" bgcolor="#eeeeee">Type</td>
        <td width="7%" bgcolor="#eeeeee">Require</td>
        <td width="6%" bgcolor="#eeeeee">Status</td>
        <td width="13%" bgcolor="#eeeeee">Description</td>
        <td width="37%" bgcolor="#eeeeee">Require message </td>
        <td width="37%" bgcolor="#eeeeee">Sort order </td>
      </tr>
	  ';if(isset($this->_data['cat_field.'])){for($i=0;$i< count($this->_data['cat_field.']);$i++){$_tpl .= '
      <tr>
        <td><input type="checkbox" name="cat_fields['.(isset($this->_data["cat_field."][$i]["code"])?$this->_data["cat_field."][$i]["code"]:'').'][chose]" '.(isset($this->_data["cat_field."][$i]["chose_checked"])?$this->_data["cat_field."][$i]["chose_checked"]:'').' value="1" />
          '.(isset($this->_data["cat_field."][$i]["code"])?$this->_data["cat_field."][$i]["code"]:'').'</td>
        <td><input name="cat_fields['.(isset($this->_data["cat_field."][$i]["code"])?$this->_data["cat_field."][$i]["code"]:'').'][name]" type="text" size="8" value="'.(isset($this->_data["cat_field."][$i]["name"])?$this->_data["cat_field."][$i]["name"]:'').'"/></td>
        <td>'.(isset($this->_data["cat_field."][$i]["type"])?$this->_data["cat_field."][$i]["type"]:'').'
        <p class="info '.(isset($this->_data["cat_field."][$i]["cls_status"])?$this->_data["cat_field."][$i]["cls_status"]:'').'">
        Default status: '.(isset($this->_data["cat_field."][$i]["status_default"])?$this->_data["cat_field."][$i]["status_default"]:'').'<br />
        Allow activate: <input name="main_fields['.(isset($this->_data["cat_field."][$i]["code"])?$this->_data["cat_field."][$i]["code"]:'').'][number]" type="text" size="8" value="'.(isset($this->_data["cat_field."][$i]["number"])?$this->_data["cat_field."][$i]["number"]:'').'" class="number" />
        </p></td>
        <td><input type="checkbox" name="cat_fields['.(isset($this->_data["cat_field."][$i]["code"])?$this->_data["cat_field."][$i]["code"]:'').'][require]" value="1" '.(isset($this->_data["cat_field."][$i]["require_checked"])?$this->_data["cat_field."][$i]["require_checked"]:'').' /></td>
        <td><input type="checkbox" name="cat_fields['.(isset($this->_data["cat_field."][$i]["code"])?$this->_data["cat_field."][$i]["code"]:'').'][status]" value="1" '.(isset($this->_data["cat_field."][$i]["status_checked"])?$this->_data["cat_field."][$i]["status_checked"]:'').' /></td>
        <td><input name="cat_fields['.(isset($this->_data["cat_field."][$i]["code"])?$this->_data["cat_field."][$i]["code"]:'').'][description]" type="text" size="8" value="'.(isset($this->_data["cat_field."][$i]["description"])?$this->_data["cat_field."][$i]["description"]:'').'" /></td>
        <td><input name="cat_fields['.(isset($this->_data["cat_field."][$i]["code"])?$this->_data["cat_field."][$i]["code"]:'').'][require_msg]" type="text" size="10" value="'.(isset($this->_data["cat_field."][$i]["require_msg"])?$this->_data["cat_field."][$i]["require_msg"]:'').'" /></td>
        <td><input name="cat_fields['.(isset($this->_data["cat_field."][$i]["code"])?$this->_data["cat_field."][$i]["code"]:'').'][sortorder]" type="text" size="10" value="'.(isset($this->_data["cat_field."][$i]["sortorder"])?$this->_data["cat_field."][$i]["sortorder"]:'').'" /></td>
      </tr>';}}$_tpl .= '
    </table></td>
  </tr>
  <tr>
    <td valign="top">Show language fields </td>
    <td>
	<p><a href="?mod=configure&act=addfield&tbl=category_ln" class="divbox">New field</a></p>
	<table width="100%" border="0" cellspacing="1" cellpadding="1">
      <tr>
        <td width="17%" bgcolor="#eeeeee">Field</td>
        <td width="6%" bgcolor="#eeeeee">Name</td>
        <td width="14%" bgcolor="#eeeeee">Type</td>
        <td width="7%" bgcolor="#eeeeee">Require</td>
        <td width="13%" bgcolor="#eeeeee">Description</td>
        <td width="37%" bgcolor="#eeeeee">Require message </td>
        <td width="37%" bgcolor="#eeeeee">Sort order </td>
      </tr>
	  ';if(isset($this->_data['ln_catfield.'])){for($i=0;$i< count($this->_data['ln_catfield.']);$i++){$_tpl .= '
      <tr>
        <td><input type="checkbox" name="ln_catfields['.(isset($this->_data["ln_catfield."][$i]["code"])?$this->_data["ln_catfield."][$i]["code"]:'').'][chose]" '.(isset($this->_data["ln_catfield."][$i]["chose_checked"])?$this->_data["ln_catfield."][$i]["chose_checked"]:'').' value="1" />
          '.(isset($this->_data["ln_catfield."][$i]["code"])?$this->_data["ln_catfield."][$i]["code"]:'').'</td>
        <td><input name="ln_catfields['.(isset($this->_data["ln_catfield."][$i]["code"])?$this->_data["ln_catfield."][$i]["code"]:'').'][name]" type="text" size="8" value="'.(isset($this->_data["ln_catfield."][$i]["name"])?$this->_data["ln_catfield."][$i]["name"]:'').'"/></td>
        <td>'.(isset($this->_data["ln_catfield."][$i]["type"])?$this->_data["ln_catfield."][$i]["type"]:'').'      </td>
        <td><input type="checkbox" name="ln_catfields['.(isset($this->_data["ln_catfield."][$i]["code"])?$this->_data["ln_catfield."][$i]["code"]:'').'][require]" value="1" '.(isset($this->_data["ln_catfield."][$i]["require_checked"])?$this->_data["ln_catfield."][$i]["require_checked"]:'').' /></td>
        <td><input name="ln_catfields['.(isset($this->_data["ln_catfield."][$i]["code"])?$this->_data["ln_catfield."][$i]["code"]:'').'][description]" type="text" size="8" value="'.(isset($this->_data["ln_catfield."][$i]["description"])?$this->_data["ln_catfield."][$i]["description"]:'').'" /></td>
        <td><input name="ln_catfields['.(isset($this->_data["ln_catfield."][$i]["code"])?$this->_data["ln_catfield."][$i]["code"]:'').'][require_msg]" type="text" size="10" value="'.(isset($this->_data["ln_catfield."][$i]["require_msg"])?$this->_data["ln_catfield."][$i]["require_msg"]:'').'" /></td>
        <td><input name="ln_catfields['.(isset($this->_data["ln_catfield."][$i]["code"])?$this->_data["ln_catfield."][$i]["code"]:'').'][sortorder]" type="text" size="10" value="'.(isset($this->_data["ln_catfield."][$i]["sortorder"])?$this->_data["ln_catfield."][$i]["sortorder"]:'').'" /></td>
      </tr>';}}$_tpl .= '
    </table>     	</td>
  </tr>
    <tr>
    <td valign="top">Cat Sort Order </td>
    <td><input name="catsort_order" type="text" id="catsort_order" value="'.(isset($this->_data["."][0]['catsort_order'])?$this->_data["."][0]['catsort_order']:'').'" /></td>
    </tr>
   <tr>
     <td> <h4><input name="act[]" type="checkbox" class="no_width" id="act[]" value="catimg" '.(isset($this->_data["."][0]['catimg_checked'])?$this->_data["."][0]['catimg_checked']:'').'> 
      Image </h4></td>
     <td>&nbsp;</td>
   </tr>
   <tr>
    <td width="200"><input name="catimg_icon[chose]" type="checkbox" class="no_width" id="catimg_icon[chose]" value="1" '.(isset($this->_data["."][0]['catimg_icon_chose'])?$this->_data["."][0]['catimg_icon_chose']:'').'>
      Icon</td>
    <td>Resize 
      <input name="catimg_icon[w]" type="text" class="no_width" id="catimg_icon[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['catimg_icon_w'])?$this->_data["."][0]['catimg_icon_w']:'').'">
      x
      
      <input name="catimg_icon[h]" type="text" class="no_width" id="catimg_icon[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['catimg_icon_h'])?$this->_data["."][0]['catimg_icon_h']:'').'"> File name: <input name="catimg_icon[name]" type="text" class="no_width" id="catimg_icon[name]" value="'.(isset($this->_data["."][0]['catimg_icon_name'])?$this->_data["."][0]['catimg_icon_name']:'').'" />
	  
	  <div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
      
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="catimg_icon[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['catimg_icon_force_resize_true'])?$this->_data["."][0]['catimg_icon_force_resize_true']:'').' />
Force resize
  <input name="catimg_icon[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['catimg_icon_force_resize_false'])?$this->_data["."][0]['catimg_icon_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="catimg_icon[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['catimg_icon_specify_none'])?$this->_data["."][0]['catimg_icon_specify_none']:'').' />
      None
      <input name="catimg_icon[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['catimg_icon_specify_min'])?$this->_data["."][0]['catimg_icon_specify_min']:'').' />
Min 
  <input name="catimg_icon[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['catimg_icon_specify_max'])?$this->_data["."][0]['catimg_icon_specify_max']:'').' />
Max </td>
    <td><input name="catimg_icon[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['catimg_icon_orginal_0'])?$this->_data["."][0]['catimg_icon_orginal_0']:'').' />
No 
  <input name="catimg_icon[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['catimg_icon_orginal_1'])?$this->_data["."][0]['catimg_icon_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>
</div></td>
  </tr>
   <tr>
    <td><input name="catimg_img[chose]" type="checkbox" class="no_width" id="catimg_img[chose]" value="1" '.(isset($this->_data["."][0]['catimg_img_chose'])?$this->_data["."][0]['catimg_img_chose']:'').'>
      Image</td>
    <td>Resize 
      <input name="catimg_img[w]" type="text" class="no_width" id="catimg_img[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['catimg_img_w'])?$this->_data["."][0]['catimg_img_w']:'').'">
      x
      <input name="catimg_img[h]" type="text" class="no_width" id="catimg_img[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['catimg_img_h'])?$this->_data["."][0]['catimg_img_h']:'').'">
	    File name: <input name="catimg_img[name]" type="text" class="no_width" id="catimg_img[name]" value="'.(isset($this->_data["."][0]['catimg_img_name'])?$this->_data["."][0]['catimg_img_name']:'').'" />
	  <div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
      
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="catimg_img[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['catimg_img_force_resize_true'])?$this->_data["."][0]['catimg_img_force_resize_true']:'').' />
Force resize
  <input name="catimg_img[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['catimg_img_force_resize_false'])?$this->_data["."][0]['catimg_img_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="catimg_img[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['catimg_img_specify_none'])?$this->_data["."][0]['catimg_img_specify_none']:'').' />
      None
      <input name="catimg_img[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['catimg_img_specify_min'])?$this->_data["."][0]['catimg_img_specify_min']:'').' />
Min 
  <input name="catimg_img[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['catimg_img_specify_max'])?$this->_data["."][0]['catimg_img_specify_max']:'').' />
Max </td>
    <td><input name="catimg_img[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['catimg_img_orginal_0'])?$this->_data["."][0]['catimg_img_orginal_0']:'').' />
No 
  <input name="catimg_img[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['catimg_img_orginal_1'])?$this->_data["."][0]['catimg_img_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>
</div></td>
  </tr>
  <tr>
    <td><input name="catimg_thumb[chose]" type="checkbox" class="no_width" id="catimg_thumb[chose]" value="1" '.(isset($this->_data["."][0]['catimg_thumb_chose'])?$this->_data["."][0]['catimg_thumb_chose']:'').'>
      Image Thumb </td>
    <td>Resize 
      <input name="catimg_thumb[w]" type="text" class="no_width" id="catimg_thumb[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['catimg_thumb_w'])?$this->_data["."][0]['catimg_thumb_w']:'').'">
      x
      <input name="catimg_thumb[h]" type="text" class="no_width" id="catimg_thumb[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['catimg_thumb_h'])?$this->_data["."][0]['catimg_thumb_h']:'').'">
	  <div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="23%" bgcolor="#eeeeee">Method</td>
    <td width="40%" bgcolor="#eeeeee">Specify</td>
    <td width="19%" bgcolor="#eeeeee">&nbsp;</td>
  </tr>
  <tr>
    <td><input name="catimg_thumb[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['catimg_thumb_force_resize_true'])?$this->_data["."][0]['catimg_thumb_force_resize_true']:'').' />
Force resize
  <input name="catimg_thumb[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['catimg_thumb_force_resize_false'])?$this->_data["."][0]['catimg_thumb_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="catimg_thumb[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['catimg_thumb_specify_none'])?$this->_data["."][0]['catimg_thumb_specify_none']:'').' />
      None
      <input name="catimg_thumb[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['catimg_thumb_specify_min'])?$this->_data["."][0]['catimg_thumb_specify_min']:'').' />
Min 
  <input name="catimg_thumb[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['catimg_thumb_specify_max'])?$this->_data["."][0]['catimg_thumb_specify_max']:'').' />
Max </td>
    <td>&nbsp;</td>
  </tr>
</table>
		</div>
	  </td>
  </tr>
   <tr>
     <td> <h4><input name="act[]" type="checkbox" class="no_width" id="act[]" value="ln_catimg" '.(isset($this->_data["."][0]['ln_catimg_checked'])?$this->_data["."][0]['ln_catimg_checked']:'').'> 
      Languages image </h4></td>
     <td>&nbsp;</td>
   </tr>
   <tr>
    <td width="200"><input name="ln_catimg_icon[chose]" type="checkbox" class="no_width" id="ln_catimg_icon[chose]" value="1" '.(isset($this->_data["."][0]['ln_catimg_icon_chose'])?$this->_data["."][0]['ln_catimg_icon_chose']:'').'>
      Icon</td>
    <td>Resize 
      <input name="ln_catimg_icon[w]" type="text" class="no_width" id="ln_catimg_icon[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_catimg_icon_w'])?$this->_data["."][0]['ln_catimg_icon_w']:'').'">
      x
      
      <input name="ln_catimg_icon[h]" type="text" class="no_width" id="ln_catimg_icon[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_catimg_icon_h'])?$this->_data["."][0]['ln_catimg_icon_h']:'').'">
	  File name: <input name="ln_catimg_icon[name]" type="text" class="no_width" id="ln_catimg_icon[name]" value="'.(isset($this->_data["."][0]['ln_catimg_icon_name'])?$this->_data["."][0]['ln_catimg_icon_name']:'').'" />
	  <div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
      
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="ln_catimg_icon[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['ln_catimg_icon_force_resize_true'])?$this->_data["."][0]['ln_catimg_icon_force_resize_true']:'').' />
Force resize
  <input name="ln_catimg_icon[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['ln_catimg_icon_force_resize_false'])?$this->_data["."][0]['ln_catimg_icon_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="ln_catimg_icon[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['ln_catimg_icon_specify_none'])?$this->_data["."][0]['ln_catimg_icon_specify_none']:'').' />
      None
      <input name="ln_catimg_icon[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['ln_catimg_icon_specify_min'])?$this->_data["."][0]['ln_catimg_icon_specify_min']:'').' />
Min 
  <input name="ln_catimg_icon[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['ln_catimg_icon_specify_max'])?$this->_data["."][0]['ln_catimg_icon_specify_max']:'').' />
Max </td>
    <td><input name="ln_catimg_icon[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['ln_catimg_icon_orginal_0'])?$this->_data["."][0]['ln_catimg_icon_orginal_0']:'').' />
No 
  <input name="ln_catimg_icon[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['ln_catimg_icon_orginal_1'])?$this->_data["."][0]['ln_catimg_icon_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>
</div></td>
  </tr>
   <tr>
    <td><input name="ln_catimg_img[chose]" type="checkbox" class="no_width" id="ln_catimg_img[chose]" value="1" '.(isset($this->_data["."][0]['ln_catimg_img_chose'])?$this->_data["."][0]['ln_catimg_img_chose']:'').'>
      Image</td>
    <td>Resize 
      <input name="ln_catimg_img[w]" type="text" class="no_width" id="ln_catimg_img[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_catimg_img_w'])?$this->_data["."][0]['ln_catimg_img_w']:'').'">
      x
      <input name="ln_catimg_img[h]" type="text" class="no_width" id="ln_catimg_img[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_catimg_img_h'])?$this->_data["."][0]['ln_catimg_img_h']:'').'">
	  
	  File name: <input name="ln_catimg_img[name]" type="text" class="no_width" id="ln_catimg_img[name]" value="'.(isset($this->_data["."][0]['ln_catimg_img_name'])?$this->_data["."][0]['ln_catimg_img_name']:'').'" />
	  
	  <div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
      
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="29%" bgcolor="#eeeeee">Method</td>
    <td width="29%" bgcolor="#eeeeee">Specify</td>
    <td width="21%" bgcolor="#eeeeee">Keep orginal image </td>
    </tr>
  <tr>
    <td><input name="ln_catimg_img[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['ln_catimg_img_force_resize_true'])?$this->_data["."][0]['ln_catimg_img_force_resize_true']:'').' />
Force resize
  <input name="ln_catimg_img[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['ln_catimg_img_force_resize_false'])?$this->_data["."][0]['ln_catimg_img_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="ln_catimg_img[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['ln_catimg_img_specify_none'])?$this->_data["."][0]['ln_catimg_img_specify_none']:'').' />
      None
      <input name="ln_catimg_img[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['ln_catimg_img_specify_min'])?$this->_data["."][0]['ln_catimg_img_specify_min']:'').' />
Min 
  <input name="ln_catimg_img[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['ln_catimg_img_specify_max'])?$this->_data["."][0]['ln_catimg_img_specify_max']:'').' />
Max </td>
    <td><input name="ln_catimg_img[orginal]" type="radio" value="0" '.(isset($this->_data["."][0]['ln_catimg_img_orginal_0'])?$this->_data["."][0]['ln_catimg_img_orginal_0']:'').' />
No 
  <input name="ln_catimg_img[orginal]" type="radio" value="1" '.(isset($this->_data["."][0]['ln_catimg_img_orginal_1'])?$this->_data["."][0]['ln_catimg_img_orginal_1']:'').' /> 
  Yes</td>
    </tr>
</table>
</div></td>
  </tr>
  <tr>
    <td><input name="ln_catimg_thumb[chose]" type="checkbox" class="no_width" id="ln_catimg_thumb[chose]" value="1" '.(isset($this->_data["."][0]['ln_catimg_thumb_chose'])?$this->_data["."][0]['ln_catimg_thumb_chose']:'').'>
      Image Thumb </td>
    <td>Resize 
      <input name="ln_catimg_thumb[w]" type="text" class="no_width" id="ln_catimg_thumb[w]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_catimg_thumb_w'])?$this->_data["."][0]['ln_catimg_thumb_w']:'').'">
      x
      <input name="ln_catimg_thumb[h]" type="text" class="no_width" id="ln_catimg_thumb[h]" size="2" maxlength="4" value="'.(isset($this->_data["."][0]['ln_catimg_thumb_h'])?$this->_data["."][0]['ln_catimg_thumb_h']:'').'">
	  <div class="resize_toggle_advance"><a href="#" onclick="return resize_toggle_advance(this);">Advandce</a>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="23%" bgcolor="#eeeeee">Method</td>
    <td width="40%" bgcolor="#eeeeee">Specify</td>
    <td width="19%" bgcolor="#eeeeee">&nbsp;</td>
  </tr>
  <tr>
    <td><input name="ln_catimg_thumb[force_resize]" type="radio" value="true" '.(isset($this->_data["."][0]['ln_catimg_thumb_force_resize_true'])?$this->_data["."][0]['ln_catimg_thumb_force_resize_true']:'').' />
Force resize
  <input name="ln_catimg_thumb[force_resize]" type="radio" value="false" '.(isset($this->_data["."][0]['ln_catimg_thumb_force_resize_false'])?$this->_data["."][0]['ln_catimg_thumb_force_resize_false']:'').' />
Flexible  </td>
    <td><input name="ln_catimg_thumb[specify]" type="radio" value="none"  '.(isset($this->_data["."][0]['ln_catimg_thumb_specify_none'])?$this->_data["."][0]['ln_catimg_thumb_specify_none']:'').' />
      None
      <input name="ln_catimg_thumb[specify]" type="radio" value="min" '.(isset($this->_data["."][0]['ln_catimg_thumb_specify_min'])?$this->_data["."][0]['ln_catimg_thumb_specify_min']:'').' />
Min 
  <input name="ln_catimg_thumb[specify]" type="radio" value="max"  '.(isset($this->_data["."][0]['ln_catimg_thumb_specify_max'])?$this->_data["."][0]['ln_catimg_thumb_specify_max']:'').' />
Max </td>
    <td>&nbsp;</td>
  </tr>
</table>
		</div>
	  </td>
  </tr>
</table>
<div class="table_list" align="right">
    <input type="submit" class="btn" name="Submit" value="Save">
</div>
</form>
<script type="text/javascript">
$(\'a.divbox\').divbox({width: 520, height: 80});
</script>

				</div>			
			</div>
		</div>
		
		<div class="ft">
			&copy; Copyright '.(isset($this->_data["."][0]['system_year'])?$this->_data["."][0]['system_year']:'').' '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'.
		</div>
	</div>
</div>

<table width="5" height="100%" cellpadding="0" cellspacing="0" border="0" class="btn_expandMenu"><tr><td>&nbsp;</td></tr></table>

<div class="cms_overlay"></div>
<noscript>
	<style type="text/css">
		.wrapper{ display: none; }
	</style>
	<div class="noscript">JavaScript must be enabled in order for you to use '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').' CMS. Please enable JavaScript by changing your browser options, then press <strong>F5</strong> to load page</div>
</noscript>


</body>
</html>'; ?>