<?php defined('_ROOT') or die('Not Allowed');
$merge_block = 6;
$_tpl = '﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--
	Website generated by CMS v02
	URL: http://demo.phpbasic.com
	Email: w2ajax@gmail.com
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" href="../template/Default/style/font-awesome.css" type="text/css" media="all">
<link rel="stylesheet" type="text/css" href="../template/Default/style/font-awesome-animation.min.css" media="all"/>

<link rel="stylesheet" type="text/css" href="template/css/common.css" />
<link rel="icon" href="../favicon.ico" type="image/x-icon" />
<title>CMS - '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</title>       
<script>var token  = \''.(isset($this->_data["."][0]['token'])?$this->_data["."][0]['token']:'').'\';</script>
<!--<script type="text/javascript" src="../plugins/jquery-1.11.1.min.js"></script>-->
<script type="text/javascript" src="../plugins/jquery-1.3.2.min.js"></script>

<script type="text/javascript" src="../template/Default/js/jquery.form.min.js"></script>



<script>var plugins_dir = \'../\';var root_dir = \''.(isset($this->_data["."][0]['root_dir'])?$this->_data["."][0]['root_dir']:'').'\'; var lang = \''.(isset($this->merge['system']['lang'])?$this->merge['system']['lang']:'').'\';</script>
<script type="text/javascript" src="../plugins/tableorder/jquery.tableorder.js"></script>
<script type="text/javascript" src="template/js/common.js"></script>
<script type="text/javascript" src="template/js/module.configure.js"></script>

<script type="text/javascript" src="../plugins/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="template/js/editor.js"></script>

<script type="text/javascript" src="../plugins/ckeditor/ckeditor.js"></script>

<script type="text/javascript" src="../plugins/divbox/divbox.js"></script>
<link rel="stylesheet" href="../plugins/divbox/css/frontend.css" type="text/css" media="screen" />
<script type="text/javascript">
var access_new = \''.(isset($this->merge['access']['new'])?$this->merge['access']['new']:'').'\';
var access_edit = \''.(isset($this->merge['access']['edit'])?$this->merge['access']['edit']:'').'\';
var access_delete = \''.(isset($this->merge['access']['delete'])?$this->merge['access']['delete']:'').'\';
</script>
<script type="text/javascript" src="../plugins/validate/validate.js"></script>
<link rel="stylesheet" href="../plugins/validate/css/validate.css" type="text/css" media="screen" />
<script type="text/javascript" src="../plugins/dateinput/dateinput.js"></script>
<!--<script type="text/javascript" src="../plugins/jquery.slug.js"></script>-->
<script type="text/javascript">
$(document).ready(function(){
	$.each($(\'form input[type=text]\'),function(i,val){
		var id = $(val).attr(\'name\');	
		id = id.replace("[","_");
		id = id.replace("]","");
		if($(val).attr(\'id\') == "" || $(val).attr(\'id\')  == undefined){
			$(val).attr(\'id\',id);
			$(val).addClass(id);
		}
	});
	//$("#name_vn").slug();
	
});
</script>

<script type="text/javascript">
$(document).ready(function(){
	$(".mtitle_vn").attr(\'maxlength\',\'60\');
	$(".mdesc_vn").attr(\'maxlength\',\'300\');
	$(\'.view_vn\').css({backgroundColor:"#fcebac"});
	$(\'.name_seo_vn\').css({backgroundColor:"#dadada"});	
});
</script>
<script type="text/javascript" src="template/skins/default/js/common.js"></script>
<link rel="stylesheet" type="text/css" href="template/skins/default/css/style.css" />
<!--[if IE]>
<style type="text/css">
tr.show{ display: block; }
</style>
<![endif]--> 

</head>
<body>

<div class="wrapper">
	<div class="container">
		<div class="hd">
			<p class="hd-r">
				Welcome <span class="hd-username">'.(isset($this->merge['login_user']['fullname'])?$this->merge['login_user']['fullname']:'').'</span>, 
				<a href="?mod=user&act=update" class="hd-profile">'.(isset($this->merge['lang']['update_profile'])?$this->merge['lang']['update_profile']:'').'</a> or 
				<a href="?mod=user&act=reset" class="hd-resetPass">'.(isset($this->merge['lang']['reset_password'])?$this->merge['lang']['reset_password']:'').'</a> <span class="hd-divider">|</span> 
				<a href="?mod=user&act=logout" class="hd-logout">'.(isset($this->merge['lang']['logout'])?$this->merge['lang']['logout']:'').'</a>
			</p>
			<a class="hd-logo" href="./">'.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</a>
		</div>
		
		<div class="ct">
			<div class="side">
				<!--<p class="menu-des">Menu</p>
				<p class="menu-desSub">
					Manage the site by this menu.<br />
					Click to collapse the menu.
				</p>-->
				';if(isset($this->_data['leftmenu.'])){for($i=0;$i< count($this->_data['leftmenu.']);$i++){$_tpl .= '
				<div class="menu '.(isset($this->_data["leftmenu."][$i]["cls_cms"])?$this->_data["leftmenu."][$i]["cls_cms"]:'').'">
					<h2 id="'.(isset($this->_data["leftmenu."][$i]["id"])?$this->_data["leftmenu."][$i]["id"]:'').'menu">'.(isset($this->_data["leftmenu."][$i]["name"])?$this->_data["leftmenu."][$i]["name"]:'').'</h2>
					'.(isset($this->_data["leftmenu."][$i]["links"])?$this->_data["leftmenu."][$i]["links"]:'').'
				</div>
				';}}$_tpl .= '
			</div>
			
			<div class="main">
				<div class="mainInner">
					<div class="breadcrumb">'.(isset($this->_data["."][0]['breadcrumb'])?$this->_data["."][0]['breadcrumb']:'').'</div>
					<div class="module_description">'.(isset($this->_data["."][0]['module_description'])?$this->_data["."][0]['module_description']:'').'</div>				
					'; if(isset($this->box['root_admin'])){ $_tpl.= '

<h3>Database</h3>
<div class="top_callFunc">
	<a href="?mod=configure&act=clear_data" onclick="return window.confirm(\'Are you sure you want to clear all data ?\');" class="btn l">Clear all data</a>
	<a href="?mod=configure&act=clear_configure" onclick="return window.confirm(\'Are you sure you want to clear all configure ?\');" class="btn l">Clear all configure</a>
	<a href="?mod=configure&act=clear_file" onclick="return window.confirm(\'Are you sure you want to clear all upload files ?\');" class="btn l">Clear upload files</a> 
	<a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=export" class="btn l divbox">Export configures</a>
</div>

<p class="sep">&nbsp;</p>

<div class="top_callFunc">
	<h3>Configure Content</h3>
	<a href="#" onclick="newConfigure(\'content\');return false;" title="New" class="btn l">New</a>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="2" class="table_list marginTop5">
  <tr>
    <th class="th-action firstColumn">Type Id </th>
    <th class="th-name">Name</th>
    <th class="th-action lastColumn">Actions</th>
  </tr>
  ';if(isset($this->_data['cfg_module.'])){for($i=0;$i< count($this->_data['cfg_module.']);$i++){$_tpl .= '
  <tr>
    <td class="th-action firstColumn"> #'.(isset($this->_data["cfg_module."][$i]["typeid"])?$this->_data["cfg_module."][$i]["typeid"]:'').'</td>
    <td class="th-name">'.(isset($this->_data["cfg_module."][$i]["attr"])?$this->_data["cfg_module."][$i]["attr"]:'').''.(isset($this->_data["cfg_module."][$i]["name"])?$this->_data["cfg_module."][$i]["name"]:'').'</td>
    <td class="th-action lastColumn">
		<a href="#" onclick="copyConfigure(\''.(isset($this->_data["cfg_module."][$i]["module"])?$this->_data["cfg_module."][$i]["module"]:'').'\','.(isset($this->_data["cfg_module."][$i]["typeid"])?$this->_data["cfg_module."][$i]["typeid"]:'').');return false;"><img src="template/images/icons_default/copy.gif" title="Copy configure" alt="" /></a> 
		<a href="?mod=content&amp;act=empty&amp;type='.(isset($this->_data["cfg_module."][$i]["typeid"])?$this->_data["cfg_module."][$i]["typeid"]:'').'" class="divbox"><img src="template/images/icons_default/clear.gif" title="Clear data" alt="" /></a> 
		<a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=module&amp;module='.(isset($this->_data["cfg_module."][$i]["module"])?$this->_data["cfg_module."][$i]["module"]:'').'&amp;typeid='.(isset($this->_data["cfg_module."][$i]["typeid"])?$this->_data["cfg_module."][$i]["typeid"]:'').'"><img src="template/images/icons_default/edit.png" width="16" height="16" border="0" /></a> | 
		<a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=export&amp;module='.(isset($this->_data["cfg_module."][$i]["module"])?$this->_data["cfg_module."][$i]["module"]:'').'&amp;typeid='.(isset($this->_data["cfg_module."][$i]["typeid"])?$this->_data["cfg_module."][$i]["typeid"]:'').'" class="divbox"><img src="template/images/icons_default/export.jpg" width="16" height="16" border="0" /></a>
		
	</td>
  </tr>
  ';}}$_tpl .= '
</table>

<p class="sep">&nbsp;</p>

<div class="top_callFunc">
	<h3>Configure HTML </h3>
	<a href="#" onclick="newConfigure(\'html\');return false;" title="New" class="btn l">New</a>
</div>

<table width="100%" border="0" cellspacing="0" cellpadding="2" class="table_list marginTop5">
  <tr>
    <th class="th-action firstColumn">Page Id </th>
    <th class="th-name">Name</th>
    <th class="th-action lastColumn">Actions</th>
  </tr>
  ';if(isset($this->_data['cfg_html.'])){for($i=0;$i< count($this->_data['cfg_html.']);$i++){$_tpl .= '
  <tr>
    <td class="th-action firstColumn"> #'.(isset($this->_data["cfg_html."][$i]["typeid"])?$this->_data["cfg_html."][$i]["typeid"]:'').'</td>
    <td class="th-name">'.(isset($this->_data["cfg_html."][$i]["name"])?$this->_data["cfg_html."][$i]["name"]:'').'</td>
    <td class="th-action lastColumn">
		<a href="#" onclick="copyConfigure(\''.(isset($this->_data["cfg_html."][$i]["module"])?$this->_data["cfg_html."][$i]["module"]:'').'\','.(isset($this->_data["cfg_html."][$i]["typeid"])?$this->_data["cfg_html."][$i]["typeid"]:'').');return false;"><img src="template/images/icons_default/copy.gif" title="Copy configure" alt="" /></a> 
		<a href="?mod=html&amp;act=empty&amp;id='.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').'" onclick="deleteConfirm(this); return false;" ><img src="template/images/icons_default/clear.gif" title="Clear data" alt="" /></a> 
		<a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=module&amp;module='.(isset($this->_data["cfg_html."][$i]["module"])?$this->_data["cfg_html."][$i]["module"]:'').'&amp;typeid='.(isset($this->_data["cfg_html."][$i]["typeid"])?$this->_data["cfg_html."][$i]["typeid"]:'').'"><img src="template/images/icons_default/edit.png" width="16" height="16" border="0" /></a> | 
		<a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=export&amp;module='.(isset($this->_data["cfg_html."][$i]["module"])?$this->_data["cfg_html."][$i]["module"]:'').'&amp;typeid='.(isset($this->_data["cfg_html."][$i]["typeid"])?$this->_data["cfg_html."][$i]["typeid"]:'').'" class="divbox"><img src="template/images/icons_default/export.jpg" width="16" height="16" border="0" /></a> '.(isset($this->_data["cfg_html."][$i]["plus"])?$this->_data["cfg_html."][$i]["plus"]:'').'</td>
  </tr>
  ';}}$_tpl .= '
</table>

<p class="sep">&nbsp;</p>

<div class="top_callFunc">
	<h3>Configure Options </h3>
	<a href="#" onclick="newConfigure(\'options\');return false;" title="New" class="btn l">New</a>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="2" class="table_list marginTop5">
  <tr>
    <th class="th-action firstColumn">Options Id </th>
    <th class="th-name">Name</th>
    <th class="th-action lastColumn">Actions</th>
  </tr>
  ';if(isset($this->_data['options.'])){for($i=0;$i< count($this->_data['options.']);$i++){$_tpl .= '
  <tr>
    <td class="th-action firstColumn">#'.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').'</td>
    <td class="th-name">'.(isset($this->_data["options."][$i]["name"])?$this->_data["options."][$i]["name"]:'').'</td>
    <td class="th-action lastColumn">
	<a href="#" onclick="copyConfigure(\''.(isset($this->_data["options."][$i]["module"])?$this->_data["options."][$i]["module"]:'').'\','.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').');return false;"><img src="template/images/icons_default/copy.gif" title="Copy configure" alt="" /></a> 
		<a href="?mod=options&amp;act=empty&amp;type='.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').'" class="divbox"><img src="template/images/icons_default/clear.gif" title="Clear data" alt="" /></a> 
		<a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=module&amp;module='.(isset($this->_data["options."][$i]["module"])?$this->_data["options."][$i]["module"]:'').'&amp;typeid='.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').'"><img src="template/images/icons_default/edit.png" width="16" height="16" border="0" /></a>  | 
		<a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=export&amp;module='.(isset($this->_data["options."][$i]["module"])?$this->_data["options."][$i]["module"]:'').'&amp;typeid='.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').'" class="divbox"><img src="template/images/icons_default/export.jpg" width="16" height="16" border="0" /></a>
	</td>
  </tr>
  ';}}$_tpl .= '
</table>

<p class="sep">&nbsp;</p>

<div class="top_callFunc">
<strong>Configure by</strong>: <select name="group" onchange="location.href=this.value">
	  ';if(isset($this->_data['cfg_group.'])){for($i=0;$i< count($this->_data['cfg_group.']);$i++){$_tpl .= '
	  <option '.(isset($this->_data["cfg_group."][$i]["selected"])?$this->_data["cfg_group."][$i]["selected"]:'').' value="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;gid='.(isset($this->_data["cfg_group."][$i]["id"])?$this->_data["cfg_group."][$i]["id"]:'').'">'.(isset($this->_data["cfg_group."][$i]["name"])?$this->_data["cfg_group."][$i]["name"]:'').'</option>';}}$_tpl .= '
	  </select>
	<a href="?mod=configure&amp;act=new" title="New" class="btn r">New</a>
</div>
	 ';}$_tpl .= '
	 <p>&nbsp;</p>
<div class="form">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_list marginTop5">
    <tr>
      <th class="th-name firstColumn">'.(isset($this->merge['lang']['name'])?$this->merge['lang']['name']:'').'</th>
	  <th class="th-name">'.(isset($this->merge['lang']['value'])?$this->merge['lang']['value']:'').'</th>
      <th class="th-action lastColumn">'.(isset($this->merge['lang']['edit'])?$this->merge['lang']['edit']:'').'</th>
    </tr>
    ';if(isset($this->_data['cfg_common.'])){for($i=0;$i< count($this->_data['cfg_common.']);$i++){$_tpl .= '
    <tr>
      <td class="th-name ">'.(isset($this->_data["cfg_common."][$i]["name"])?$this->_data["cfg_common."][$i]["name"]:'').'</td>
      <td class="th-name">'.(isset($this->_data["cfg_common."][$i]["value"])?$this->_data["cfg_common."][$i]["value"]:'').'</td>
      <td class="th-action lastColumn">
	  	<a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=update&amp;code='.(isset($this->_data["cfg_common."][$i]["code"])?$this->_data["cfg_common."][$i]["code"]:'').'&gid='.(isset($this->_data["cfg_common."][$i]["group_id"])?$this->_data["cfg_common."][$i]["group_id"]:'').'"><img src="template/images/icons_default/edit.png" alt="Edit" width="16" height="16" border="0" /></a></td>
    </tr>
    ';}}$_tpl .= '
  </table>
</div>
<script type="text/javascript">
	$(\'a.divbox\').divbox({type: \'ajax\',width: 600,height: 300, caption: false,btn_closed:\'#divbox_frame .closed,#divbox_frame .btn_closed\'});
</script>
				</div>			
			</div>
		</div>
		
		<div class="ft">
			&copy; Copyright '.(isset($this->_data["."][0]['system_year'])?$this->_data["."][0]['system_year']:'').' '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'.
		</div>
	</div>
</div>

<table width="5" height="100%" cellpadding="0" cellspacing="0" border="0" class="btn_expandMenu"><tr><td>&nbsp;</td></tr></table>

<div class="cms_overlay"></div>
<noscript>
	<style type="text/css">
		.wrapper{ display: none; }
	</style>
	<div class="noscript">JavaScript must be enabled in order for you to use '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').' CMS. Please enable JavaScript by changing your browser options, then press <strong>F5</strong> to load page</div>
</noscript>


</body>
</html>'; ?>